accounts/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from .import views

urlpatterns = [
	path('signup/', views.register, name="register"),
	path('profile/', views.profile_view, name='profile'),

	path('login/', views.login_view, name="login"),
	path('logout/', views.logout_view, name="logout"),
	path('profile/update/', views.profile_form, name="profile_update"),

	# using default auth view for pasword change and reset
	path('change_password/', auth_views.PasswordChangeView.as_view()),
	path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),
	path('password_reset/', auth_views.PasswordResetView.as_view()),
	path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
	path('reset/<uidb64>/<token>/',
		auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
	path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

animalsite/urls.py
from django.conf import settings
from django.contrib import admin
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path, include


urlpatterns = [
	path("", include('post.urls')),
	path("accounts/", include('accounts.urls')),
	path('admin/', admin.site.urls),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

post/urls.py
from django.urls import path
from django.views.generic import TemplateView

from . import views

urlpatterns = [
    path("", views.index, name='home'),
    path("services/", views.services, name='services'),
    path("contacts/", views.contacts, name='contacts'),
    path("search/", views.search, name='search'),
    path("new-post/", TemplateView.as_view(template_name='post/post-type.html'), name='new-post'),
    path('product/<cat_slug>/', views.product_page, name='product_page'),
    path("product/detail/<pk>/", views.product_detail, name='product_detail'),
    path("post/detail/<pk>/", views.post_detail_view, name='post-detail'),
    path("post/list/<post_type>/", views.post_list_view, name='post-list'),
    path("form/<post_type>/", views.form_view, name='post-form'),
]

accounts/models.py
from django.contrib.auth.models import User
from django.db import models


class Profile(models.Model):
	user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
	name = models.CharField(max_length=255, blank=True)
	contact = models.CharField(max_length=20, blank=True)
	photo = models.ImageField(upload_to='images/profile/', null=True, blank=True)

	created_date = models.DateTimeField(auto_now_add=True)
	updated_date = models.DateTimeField(auto_now=True)
	is_active = models.BooleanField(default=True)

	def __str__(self):
		return self.name

post/models.py
from django.contrib.auth.models import User
from django.db import models

from mptt.models import MPTTModel, TreeForeignKey


class BasicModel(models.Model):
	created_date = models.DateTimeField(auto_now_add=True)
	updated_date = models.DateTimeField(auto_now=True)
	is_active = models.BooleanField(default=True)
	is_featured = models.BooleanField(default=False)

	class Meta:
		abstract = True


class Category(BasicModel, MPTTModel):
	"""
	The category of the pet for filtering
	"""
	parent = TreeForeignKey('self', on_delete=models.SET_NULL, null=True, blank=True, related_name='children')
	title = models.CharField(max_length=100)
	slug = models.SlugField()

	def __str__(self):
		return self.title 

	def get_absolute_url(self):
		return f"/{self.slug}/"


class Product(BasicModel):
	category = models.ForeignKey(Category, on_delete=models.CASCADE)
	title = models.CharField(max_length=100)
	image = models.ImageField(upload_to='images/category/', null=True, blank=True)
	description = models.TextField()

	def __str__(self):
		return self.title	


class Post(BasicModel):
	TYPE_CHOICES = [('lost', 'Lost'), ('found', 'Found'), ('sell', 'Sell')]
	post_type = models.CharField(max_length=5, choices=TYPE_CHOICES)

	posted_by = models.ForeignKey(User, related_name='posts', on_delete=models.SET_NULL,
									null=True, blank=True)
	# user who
	closed_to = models.ForeignKey(User, related_name='closed_posts', on_delete=models.SET_NULL,
									null=True, blank=True)

	category = models.ForeignKey(Category, on_delete=models.CASCADE)
	title = models.CharField(max_length=100, blank=True)
	code = models.CharField(max_length=15, unique=True)
	description = models.TextField()
	price = models.DecimalField(max_digits=15, decimal_places=2, null=True, blank=True)
	location = models.CharField(max_length=255)
	image = models.ImageField(upload_to='images/site/', null=True, blank=True)

	def __str__(self):
		return '{}-{}'.format(self.post_type, self.id)

	def save(self, *args, **kwargs):
		if self.id is None:
			super().save(*args, **kwargs)
		code = '{}-{}'.format(self.post_type, self.id)
		self.code = code
		super().save(*args, **kwargs)


class PostReactions(BasicModel):
	user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
	post = models.ForeignKey(Post, on_delete=models.CASCADE)
	description = models.TextField()
	seen = models.BooleanField(default=False)


class ContactMessage(models.Model):
	user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
	name = models.CharField(max_length=255)
	email = models.EmailField()
	contact = models.CharField(max_length=20)
	address = models.CharField(max_length=255, blank=True)
	message = models.TextField()
	created_date = models.DateTimeField(auto_now_add=True)

	def __str__(self):
		return '{}-{}'.format(self.id, self.name)

accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Profile


class UserForm(forms.ModelForm):

	password1 = forms.CharField(label='Password', widget=forms.PasswordInput)
	password2 = forms.CharField(label='Password confirmation', widget=forms.PasswordInput)

	class Meta:
		model = User
		fields = ('username', 'email')

	def clean_password2(self):
		password1 = self.cleaned_data.get("password1")
		password2 = self.cleaned_data.get("password2")

		if password1 and password2 and password1 != password2:
			raise forms.ValidationError("Passwords don't match")
			return password2

	def clean_username(self):
		return self.cleaned_data.get("username").lower()

	def clean_email(self):
		return self.cleaned_data.get("email").lower()

	def save(self, commit=True):
		user = super().save(commit=False)
		user.set_password(self.cleaned_data.get("password1"))
		if commit:
			user.save()
		return user


class LoginForm(forms.Form):
	username = forms.CharField()
	password = forms.CharField(widget=forms.PasswordInput())

	def clean_username(self):
		return self.cleaned_data.get("username").lower()

	class Meta:
		fields = ('email','password')


class ProfileForm(forms.ModelForm):
	class Meta:
		model = Profile
		fields = ['name', 'contact','photo']

accounts/views.py
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect, render

from post.models import Post
from .models import Profile
from .forms import LoginForm, ProfileForm, UserForm


def register(request):
    if request.user.is_authenticated:
    	return redirect('home')
    form = UserForm(request.POST or None)
    profile_form = ProfileForm(request.POST or None)
    if request.method == 'POST':
        if form.is_valid() and profile_form.is_valid():
            user = form.save()
            profile = profile_form.save(commit=False)
            profile.user = user
            profile.save()
            messages.info(request, "created successfully")
            return redirect('login')
        print(form.errors)
        messages.error(request, "Something is wrong!")
    return render(request, 'accounts/register.html', {'form':form})



def login_view(request):
	if request.user.is_authenticated:
		return redirect('/')
	form = LoginForm(request.POST or None)
	if request.method == 'POST':
		print("a")
		if form.is_valid():
			username = request.POST['username']
			password = request.POST['password']
			user = authenticate(username=username, password=password)
			if user is not None:
				login(request, user)
				return redirect(request.GET.get('next', '/'))
		print(form.errors)
		messages.error(request, 'Invalid login credentials!')
	return render(request, 'accounts/login.html', {'forms': form})


def logout_view(request):
	logout(request)
	return redirect('/')



@login_required
def profile_view(request):
	deac_id = request.GET.get('deactivate')
	if deac_id:
		try:
			post = Post.objects.get(id=deac_id)
		except Exception as e:
			print('Exception: {}'.format(e))
		else:
			post.is_active = False
			post.save()
		return redirect('profile')
	posts = Post.objects.filter(posted_by=request.user).order_by('-is_active', '-created_date')
	return render(request, 'accounts/profile.html', {'posts': posts})


def profile_form(request):
    p_form = ProfileForm(instance=request.user.profile)
    if request.method == 'POST':
        p_form = ProfileForm(request.POST, request.FILES, instance=request.user.profile)
        if p_form.is_valid():
            p_form.save()
            messages.success(request, "Updated Successfully!")
            return redirect('home')
        else:
            p_form = ProfileForm(instance=request.user.profile)
    context = {'p_form': p_form}
    return render(request, 'accounts/profile_update.html', context)

accounts/templates/accounts/login.html
{% extends 'post/base.html' %}
{% load static %}
{% block content %}<br><br>
<section id="ind-sec-cat">
    <div class="container">
<div class="container">

        <div class="row">

            <div class="col-sm-6">
                <div class="signup-form"><!--sign up form-->
                    <h2>Login to your account</h2>
                    <form method="POST" class="form-horizontal">
                        {% csrf_token %}
                        <label>User Name: </label><input type="text" placeholder="Name" name="username"/>
                       <label>Password:</label> <input type="password" placeholder="Password" name="password" />
                        <button type="submit" class="btn btn-default">Login</button>
                    </form>
                </div><!--/sign up form-->
            </div>
        </div>
    </div>

    </div>
</section>
{% endblock %}

accounts/templates/accounts/profile.html
{% extends 'post/base.html' %}
{% load static %}
{% block content %}
<h3>My Posts</h3>
{% if posts %}
<a href="{% url 'profile_update' %}" class="btn btn-primary" style="margin-bottom: 20px;">Update Profile</a>
<table class="table table-bordered">
    <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Title</th>
            <th scope="col">Type</th>
            <th scope="col">Category</th>
            <th scope="col">Status</th>
            <th scope="col">View Post</th>
        </tr>
    </thead>
    <tbody>
        {% for post in posts %}
        <tr>
            <th scope="row">{{ forloop.counter }}</th>
            <td>{{ post.title }}</td>
            <td>{{ post.get_post_type_display }}</td>
            <td>{{ post.category }}</td>
            <td>{{ post.is_active|yesno:"Active,Inactive,Unknown" }} {% if post.is_active %} <a class='btn btn-warning ml-0 float-right' href="?deactivate={{ post.id }}">Deactivate</a>{% endif %}</td>
            <td><a href="{% url 'post-detail' post.id %}" class='btn btn-default'>View</a></td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% else %}
<p>No posts till Now</p>
{% endif %}

{% endblock %}

accounts/templates/accounts/profile_update.html
{% extends 'post/base.html' %}
{% load static %}
{% block content %}<br><br>
<section id="ind-sec-cat">
    <div class="container">
<div class="container">

        <div class="row">

            <div class="col-sm-6">
                <div class="signup-form"><!--sign up form-->
                    <h2>Update Profile Picture</h2>
                    <form method="POST" class="form-horizontal" enctype="multipart/form-data">
                        {% csrf_token %}
                       
                        {{p_form.as_p}}
                    
                    
                        <button type="submit" class="btn btn-default">Update</button>
                    </form>
                </div><!--/sign up form-->
            </div>
        </div>
    </div>

    </div>
</section>
{% endblock %}

accounts/templates/accounts/register.html
{% extends 'post/base.html' %}
{% load static %}
{% block content %}<br><br>
<section id="ind-sec-cat">
    <div class="container">
<div class="container">

        <div class="row">

            <div class="col-sm-6">
                <div class="signup-form"><!--sign up form-->
                    <h2>New User Signup!</h2>
                    <form method="POST" class="form-horizontal">
                        {% csrf_token %}
                        <label>Username: </label><input type="text" placeholder="Name" name="username"/>
                        <label>Full Name: </label><input type="text" placeholder="Name" name="name"/>
                       <label>Contact Number:</label> <input type="text" placeholder="Contact Number" name="contact" />
                        <label>Email Address:</label><input type="email" placeholder="Email Address" name="email" />
                       <label>Password:</label> <input type="password" placeholder="Password" name="password1" />
                      <label>Conform Password: </label>  <input type="password" placeholder="Confirm Password" name="password2"/>
                        <button type="submit" class="btn btn-default">Signup</button> <a href="btn btn-default float-right">New User?</a>
                    </form>
                </div><!--/sign up form-->
            </div>
        </div>
    </div>

    </div>
</section>
{% endblock %}